services:
  sing-box-configurer:
    image: docker.io/lanfix/sing-box-configurer:v0.0.7
    container_name: sing-box-configurer
    restart: always
    network_mode: host
    ports:
      - 8080:8080
    volumes:
      - ./sing-box-configurer.json:/app/config.json:ro
      - ./rules.json:/app/rules.json:rw
      - ./sing-box.json:/etc/sing-box/config.json:rw
    depends_on:
      - docker-controller

  docker-controller:
    image: docker.io/lanfix/docker-controller:v0.0.1
    container_name: docker-controller
    restart: always
    ports:
      - 8081:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker-controller.json:/app/config.json:ro

  sing-box:
    image: ghcr.io/sagernet/sing-box:v1.14.0
    container_name: sing-box
    restart: always
    network_mode: host
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
    labels:
      - app=sing-box
      - managed=true
    depends_on:
      - sing-box-configurer
    volumes:
      - ./sing-box.json:/etc/sing-box/config.json
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

  cron-scheduler:
    image: whefter/cron:latest
    container_name: cron-scheduler
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CRON_DAILY_RESTART=0 6 * * * docker restart sing-box
